### ISSUE TITLE
WP 3.8 Compatibility

### ISSUE THREAD

**Issue by jjeaton** [jjeaton/wp-veriteco-timeline#9]
Most likely issues with JS

Also: [http://wordpress.org/support/topic/plugin-stopped-working-after-wp-38-update?replies=2](http://wordpress.org/support/topic/plugin-stopped-working-after-wp-38-update?replies=2)

**Comment by titaniumbones** [comment]
Can we close this bug?  The OP actually had #4 , the fix for which I just submitted as a pull request.

**Comment by jjeaton** [comment]
@titaniumbones I'm going to keep it open for now until we can fix #8 to ensure that nothing else with 3.8 causes issues. For the most part though, it's already compatible.

**Comment by jjeaton** [comment]
No real issues with 3.8
